[package]
name = "polite-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "polite_cli"
path = "src/lib.rs"

[[bin]]
name = "polite"
path = "src/main.rs"

[dependencies]
polite-diag = { workspace = true }
polite-js = { workspace = true }
polite-vocab = { workspace = true }
polite-syntax = { workspace = true }
polite-check = { workspace = true }
polite-ir = { workspace = true }
polite-run = { workspace = true }
polite-std = { workspace = true }
